AllCops:
  Include:
    - rubocop-rspe

AllCops:
  TargetRubyVersion: 3.0

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/spec_helper.rb'
